### ISSUE TITLE
sum c

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/no_term#2]
non so da dove cominciare ... è pieno di errori

**Comment by tonyiovino** [comment]
Si, avevo fatto di fretta, ora mi concentro, e cerco di farlo migliore.

**Comment by tonyiovino** [comment]
Ho sostituzione dalle 9:00 alle 11:00, e di nuovo alle 13:00. Se posso
venire e non disturbo, potete dirmi in che aula siete?

Il Ven 22 Nov 2019 15:56 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Alle 10 Lab 2, alle 13 1.10

Il gio 28 nov 2019, 09:44 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
E giustamente la notofica del vostro messaggio, mi è arrivata ora...
Comunque penso vi siate dimenticare di passarmi i libri. ✌

Il giorno gio 28 nov 2019 alle ore 08:51 Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Come posso rendere codice il "se esiste il file"?

**Comment by FabioZTessitore** [comment]
controlla la mail

**Comment by tonyiovino** [comment]
Sisi, ho controllato. Ma non ho capito cosa devo mettere nella condizione.

**Comment by FabioZTessitore** [comment]
allora riguarda la guida

**Comment by tonyiovino** [comment]
...non ci credo. Mi è crashato il pc.
*murderous instinct: mode on.*

Il Ven 29 Nov 2019 18:15 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
riprendiamo i lavori?

**Comment by tonyiovino** [comment]
Manco a farlo apposta, sto cercando di capire come scrivere nei file.
Quindi si!

Il Sab 14 Mar 2020, 17:38 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Stavo pulendo le mail quando vedo la sua... Mi scusi di averla fatta
aspettare.

Il Mer 25 Mar 2020, 21:08 HitLocker Official <
antonioiovino2004tony@gmail.com> ha scritto:

**Comment by tonyiovino** [comment]
Fatto, ma il programma funziona solo se "sum.dat" esiste gia'

**Comment by tonyiovino** [comment]
E' da ieri che ci ragiono...

**Comment by FabioZTessitore** [comment]
infatti bisogna controllare

Il giorno gio 26 mar 2020 alle ore 15:25 tonyiovino <
notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Io so qual e' il problema, ma non so come risolverlo.
Righe 12-13 oppure 18.

**Comment by FabioZTessitore** [comment]
```c
        FILE *f;	 
	int num = 0;
	int f_num = 0;

	f = fopen("sum.dat","r");                                             /* qui apri il file */
	fscanf(f, "%d", &f_num);                                            /* qui, senza controlli, vai a leggere */

	printf("Lettura dal file sum.dat in corso...\n");
	printf("Valore corrente: %d\n\n", f_num);

	if(f) {                                                                          /* qui controlli */
		FILE *f = fopen("sum.dat","r");                          /* però riapri il file!!! */
		fscanf(f, "%d", &f_num);
	}
```

**Comment by tonyiovino** [comment]
E' un ora che sto fissando il codice e ragionandoci sopra... Non ho capito, non ci arrivo.

**Comment by tonyiovino** [comment]
Mi e' venuta un idea... Provo e le faccio sapere come e' andata.

**Comment by tonyiovino** [comment]
Finalmente ho capito.

**Comment by tonyiovino** [comment]
Stavo modificando le scritte, che in base alla scelta del `if` cambia.
Ora lo pubblico, anche se penso ci sia uno spreco di risorse nelle righe 23-25 e 36-38.

**Comment by FabioZTessitore** [comment]
va quasi bene, c'è solo qualcosina da aggiustare.
Ricorda che nel file deve esserci solo un valore, che non ha senso aprirlo se poi non devi farci niente ecc

**Comment by tonyiovino** [comment]
Ho dimenticato lo standard error.
E non ho capito cosa intenda con "un solo valore".

Il Ven 27 Mar 2020, 05:49 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Il file è semplicemente un file di testo. Se lo apri ci deve essere un
numero. Uno solo.
Es.
42

Il ven 27 mar 2020, 12:32 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
AAH, non avevo visto. Sara' perche' avro' scritto piu' volte. Ora controllo.

**Comment by tonyiovino** [comment]
La consegna dell'esercizio non dice di mettere lo stderr, devo inserirlo lo stesso?

**Comment by FabioZTessitore** [comment]
La scrittura su stderr è una cosa che hai imparato. Quindi la puoi usare
quando necessario (scrittura di messaggi di errore)

Il ven 27 mar 2020, 17:37 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Essa puo' essere usata solo con `fprintf` o anche con `printf`?

**Comment by FabioZTessitore** [comment]
allora non l'hai imparato! :-)
printf non permette di specificare il file di output, utilizza automaticamente stdout

**Comment by FabioZTessitore** [comment]
bisogna rivedere un po' il blocco else iniziale.
poi alla fine, non serve andare a leggere il valore scritto nel file

**Comment by tonyiovino** [comment]
Fatto, ma non ho capito la differenza nell'utilizzare `fprintf(stdout, "Hello");`, `fprintf(stderr, "ERRORE!");` e `printf("Ho eseguito l'azione.");`.
Alla fine esce sempre alla stessa maniera di `printf`... Perdonate l'_igniorantita_. XD

**Comment by FabioZTessitore** [comment]
allora non hai capito le lezioni sulla redirezione dell'output

**Comment by FabioZTessitore** [comment]
```c
fprintf(stdout, "Hello");
printf("Ho eseguito l'azione.");
```
Queste due sono equivalenti (printf stampa su stdout automaticamente)


```c
fprintf(stderr, "ERRORE!");
```
Questa stampa sullo standard error


Ora se stdout e stderr coincidono (come normalmente è, fanno sono entrambi riferimento al terminale), non vedi differenza nell'applicazione. Però se fai la redirezione dell'output cambia.
Ad esempio potresti visualizzare sul terminale l'output normale (stdout) e mettere in un file gli errori (stderr non è più il terminale ma un file), o viceversa

**Comment by tonyiovino** [comment]
Ah, si, non ci avevo pensato (redirezione dell'output). Grazie!

**Comment by FabioZTessitore** [comment]
### bisogna rivedere un po' il blocco else iniziale
Hai fatto pulizia ma non abbastanza, perché apri il file in scrittura qui? Verrà comunque aperto dopo.

### poi alla fine, non serve andare a leggere il valore scritto nel file
Dopo che hai scritto nel file, perché vai a leggere cosa c'è dentro?

**Comment by tonyiovino** [comment]
1) Fatto, sara' stata la distrazione.
2) Vero, era l'abitudine di scrivere la `scanf` dopo una `printf`... Sorry.

**Comment by FabioZTessitore** [comment]
la riga 24 ora deve essere spostata (nell'else non viene aperto il file)

la riga 34 deve sparire, non so come dirtelo

**Comment by tonyiovino** [comment]
VERO... Avevo pensato "Vabbe... l'ho aperto fuori l'if e dovra' essere chiuso fuori", ma non ci ho pensato che tanto si chiudera' lo stesso...
Riguardo alla scanf, l'ho tolta, ma non ho postato su github.
