### ISSUE TITLE
thusum py

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/no_term#3]
cerchiamo di ragionare.

riga 3 non significa niente perché f non esiste

poi fai prima l'if su f e poi dici chi è f. Ti pare normale?

**Comment by tonyiovino** [comment]
Appunto, come si fa a dichiarare un file?

Il Sab 28 Mar 2020, 16:55 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
le variabili in python non si dichiarano

**Comment by tonyiovino** [comment]
Comunque sapevo che c'era qualcosa che non andava nella linea 3 (lo si vedeva anche dal terminale), pero' dovevo spegnere la macchina.

**Comment by tonyiovino** [comment]
_name 'os' is not defined_, cosa significa?

**Comment by FabioZTessitore** [comment]
l'interprete ha trovato questo nome nel tuo programma e non sa cosa sia

**Comment by tonyiovino** [comment]
Devo importare qualche libreria? Perché nella consegna, c'è un icona più
grande della pagina che dice di usarlo... 😂

Il Sab 28 Mar 2020, 20:59 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
```py
import os

f = 'sum.dat'                                  # ok l'idea di memorizzare il nome

if os.path.isfile(f):
	f = open('sum.dat', 'r');         # ma poi perche' ricicli f con una cosa diversa?
	string = f.readline()
	f_num = int(string)
	print('Lettura dal file sum.dat in corso...')
	print('Valore corrente: ', f_num)
	print('Inserisca il valore da sommare: ')

	f.close()
else:
	print('Il file sum.dat non esiste.\nCreare un nuovo valore: ')

num = input()
num = int(num)
somma = f_num + num                # f_num quanto vale? attento a quello che rispondi
somma = str(somma)

f = open('sum.dat', 'w')

f.write(somma)

print('Ho letto il valore ', somma)

print('Salvataggio nel file sum.dat in corso...')

f.close()
```
